title: "[optional] Write a custom validator for the Author field"
position: 5
category: General
preparation: false
estimated_time_in_minutes: 15
always_unlocked: false
git_tag_completed: solve--write-custom-validator
