title: Integrate the Form for an Edit Page
position: 70
category: General
preparation: false
estimated_time_in_minutes: 20
always_unlocked: false
git_tag_completed: solve--integrate-form-for-edit-page
